In [73]:
import pandas as pd
import numpy as np
from nnfs.datasets import spiral_data

In [74]:
X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

In [75]:
X, y = spiral_data(100,3)

In [95]:

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

class Loss: 
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

class Loss_CategoricalCrossEntropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)
        
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

X,y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function = Loss_CategoricalCrossEntropy()
loss = loss_function.calculate(activation2.output, y)
print("Loss: ", loss)

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
Loss:  1.0979301371211463


In [84]:
layer1 = Layer_Dense(2, 5)
activation1 = Activation_ReLU()

In [89]:
layer1.forward(X)
print(layer1.output)
print("\n")
activation1.forward(layer1.output)
print(activation1.output)

[[ 0.          0.          0.          0.          0.        ]
 [-0.00091765 -0.00213139  0.00026712 -0.00030707  0.00081664]
 [-0.00218342 -0.00304139  0.00052093 -0.00092461  0.00364887]
 ...
 [ 0.04452348  0.21504044 -0.01926392  0.00423289  0.05417796]
 [ 0.0474945   0.21839344 -0.0199284   0.00556607  0.04855283]
 [ 0.02631109  0.20686997 -0.01588995 -0.00512278  0.09906577]]


[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.00026712 0.         0.00081664]
 [0.         0.         0.00052093 0.         0.00364887]
 ...
 [0.04452348 0.21504044 0.         0.00423289 0.05417796]
 [0.0474945  0.21839344 0.         0.00556607 0.04855283]
 [0.02631109 0.20686997 0.         0.         0.09906577]]
